### ISSUE TITLE
Raspbian stretch support

### ISSUE THREAD

**Issue by thijstriemstra** [FooDeas/raspberrypi-ua-netinst#88] opened 2017-09-04 21:45 UTC
Is https://www.raspberrypi.org/blog/raspbian-stretch/ supported?

**Comment by thijstriemstra** [comment] 2017-09-04 22:16
When running `update.sh` it just hangs:

```
$ ./update.sh 
Setting up gpg... 
gpg: keyring `gnupg/secring.gpg' created
gpg: keyring `gnupg/pubring.gpg' created
gpg: gnupg/trustdb.gpg: trustdb created

Downloading raspbian.public.key.
raspbian.public.key            100%[====================================================>]   1,73K  --.-KB/s    in 0s      
Checking key file 'raspbian.public.key'... OK
Importing 'raspbian.public.key' into keyring... OK

Downloading raspberrypi.gpg.key.
raspberrypi.gpg.key            100%[====================================================>]   1,68K  --.-KB/s    in 0,003s  
Checking key file 'raspberrypi.gpg.key'... OK
Importing 'raspberrypi.gpg.key' into keyring...OK

Downloading Release file and its signature...
```

**Comment by thijstriemstra** [comment] 2017-09-05 13:59
`jessie` is also hardcoded: https://github.com/FooDeas/raspberrypi-ua-netinst/blob/devel/update.sh#L19

**Comment by thijstriemstra** [comment] 2017-09-05 14:07
> When running update.sh it just hangs

This was an error on my part, my `build.conf` contained a non-existing cache server, fixed now.

> jessie is also hardcoded

This can also be overridden in `build.conf`. My `build.conf` looks like:

```
mirror_raspbian_cache=192.168.178.27:3142
mirror_raspberrypi_cache=192.168.178.27:3142
release=stretch
```

And `update.sh` now dies with this error:

```
ERROR: Unable to find all required packages in package list!
Missing packages: 'libssl1.0.0'
```

**Comment by thijstriemstra** [comment] 2017-09-05 14:22
> Missing packages: 'libssl1.0.0'

Looks like there's now a `libssl1.1` and a `libssl1.0.2` in stretch, `libssl1.0.0` is gone. Which one should we use?

I guess newer is better so I'll give 1.1 a try.

**Comment by thijstriemstra** [comment] 2017-09-05 14:27
> I guess newer is better so I'll give 1.1 a try.

That worked with following patch:

```diff
diff --git a/update.sh b/update.sh
index 863d910..98efb0d 100755
--- a/update.sh
+++ b/update.sh
@@ -76,7 +76,7 @@ packages+=("libpcsclite1")
 packages+=("libselinux1")
 packages+=("libslang2")
 packages+=("libsmartcols1")
-packages+=("libssl1.0.0")
+packages+=("libssl1.1")
 packages+=("libtinfo5")
 packages+=("libuuid1")
 packages+=("zlib1g")
```

But now `build.sh` dies with the following error:

```
$ ./build.sh 
cp: cannot stat 'tmp/sbin/mkfs.btrfs': No such file or directory
```

Any idea @FooDeas?

**Comment by FooDeas** [comment] 2017-09-05 21:07
Using the current installer with stretch in the installer-config should already work and install Debian stretch as intended!
Porting the installer environment itself to stretch is a bit more work. I've tried that some time ago but hadn't enough time to finish. I'll give it another try very soon!

**Comment by emaayan** [comment] 2017-09-10 12:57
i'm not sure i follow, is it possible to use stretch from the image that comes with it? 

cause if this means using stretch that gets downloaded from the mirrors, that could be a problem cause those packages keep getting updated.

**Comment by h3rald** [comment] 2017-09-10 16:54
I specified release=stretch in the installer-config.txt file and I got this error:

`Unknown suite stretch`

Any ideas? I would like to perform an unattended installation of a minimal raspbian stretch release... did anyone succeed in doing so?

**EDIT**

Here's where it hangs exactly:

```
Waiting 5 seconds.....
Waiting for /dev/mmcblk0... 
  Disk /dev/mmcblk0: 14.9 GiB, 15931539456 bytes, 31116288 sectors
  Disklabel type: dos
  Disk identifier: 0x2b2899ba
OK
Applying new partition table... OK
Initializing /boot as vfat... OK
Copying /boot files in... OK
Loading f2fs module... OK
Initializing / as f2fs... OK
Mounting new filesystems... OK

Starting install process...
  E: Unknown suite stretch

  ERROR: 1

Error: The installation could not be completed!
```
Could it be something similar to [this issue](https://github.com/debian-pi/raspbian-ua-netinst/issues/451)?

**Comment by FooDeas** [comment] 2017-09-10 21:56
Yes - it seems that cdebootstrap is the problem. I took one our struggling to include curl to the installer environment.
With porting to stretch, I need a more efficient package resolve/copy solution. The current way to do that is horrible!

**Comment by h3rald** [comment] 2017-09-11 06:25
But as far as I can tell from reading online, the latest version of cdebootstrap doesn't have any problem... so is there any way to manually substitute the .deb package with a more recent one? Does the installer cache the downloaded packages somewhere?

Someone managed to do it with the raspbian-ua-installer, I wonder if it is possible with this installer as well -- especially knowing that you already sorted out curl installation.

**Comment by malignus** [comment] 2017-09-19 19:51
I've got it working now after resolving all the curl dependencies.

**Comment by thijstriemstra** [comment] 2017-09-19 23:16
@malignus, can you make a pull request..?

**Comment by malignus** [comment] 2017-09-20 09:28
@thijstriemstra, done

**Comment by emaayan** [comment] 2017-09-26 16:24
hi.. so what's the status of this issue? can this installer be used with a stretch image?

**Comment by FooDeas** [comment] 2017-09-30 13:17
90% is done - I'm still fixing some issues.

**Comment by FooDeas** [comment] 2017-09-30 17:03
I applied all needed changes from malignus' PR and got cdebootstrap working.
The only issue during the installation is setting the timezone. I'll check that later. More important:

The system reboots - loads firmware, kernel and - stops with "can't access tty; job control turned off".
The system partition is mounted (read only?) and readable. I can execute shell commands and load bash.
I need someone, who has a short look at it.

**Comment by malignus** [comment] 2017-09-30 19:11
There is a symlink missing from /sbin/init to systemd. Please have a look into my install.sh

**Comment by FooDeas** [comment] 2017-09-30 19:54
I already tried that - and switched the "ln -s" arguments. I just used the right order now.
Success. Thanks!

**Comment by FooDeas** [comment] 2017-09-30 21:52
It's done.
If no bugs get reported here, I will release v2.0.0 final on Thursday.

**Comment by mpmc** [comment] 2017-10-04 00:16
@FooDeas (and everyone else involved) thanks for getting raspberrypi-ua-netinst working with Stretch! It's a shame that the original netinst is lagging behind & I'm guessing there is no way to merge up? :sob:  

Anyway, I ran into some issues initially, but everything seems to be working as expected & the additional options are fantastic!

Some (minor) issues.

* If IPv6 is enabled on the router but not configured to route IPv6 the install doesn't appear to complete and eventually gives up. I had to configure openwrt to assign IPv6 addresses (I'd previously disabled DHCPv6 as it caused a few issues on the network last time I used it). While this isn't an issue with the installer, it would be nice if there was an option to ignore ipv6 during install.

* Text appears "chopped off" during install (mainly when retrieving/configuring packages), I say chopped off but what appears to happen is the text is only partially printed with the cursor blinking. It however eventually catches up & prints the rest (along with other output). I observed this on 2 Pi's (Pi B+ 512M / Pi 2 B 1GB). I have a capture of the install if anyone would like to see it.

I initially did a blind install on the Pi 2B 1G, but that failed due to the aforementioned IPv6 issue. So used my older Pi B+ 512M (which is hooked up to a capture box) to see what the problem was, finally twigged that it was an IPv6 issue, fixed the network & the install completed in about 25 minutes! The newer Pi2 (not wifi) took circa 10 mins if that. 

Next I'm doing an install on:

* Original 256M Pi (One of the first production batch)
* Another 3x Pi 2 1G
* And a Pi Zero W.

I will report back if I encounter any issues, but hopefully it's clear sailing from here.

**Comment by FooDeas** [comment] 2017-10-04 05:48
Thanks!
Can you attach a screenshot of the problematic openwrt IPv6 settings and the installer log?

**Comment by mpmc** [comment] 2017-10-04 08:43
@FooDeas Unfortunately I didn't keep the log, I don't think the installer actually gives up, it just feels like it does, as each HTTP request takes an age to finally fallback to IPv4. I suspect it would complete, but how long is anyone's guess, I waited up to 2 hours before deciding something was wrong & pulled the plug. I could break my network again & record another install if it's really needed.

This problem isn't unique to this installer as I remember other HTTP requests failing on my Orange Pi's when running apt update. So I think the combinations of disabling DHCPv6 & the DNS lookups failing.

As for the problematic IPv6 settings I'd just turned off "Router Advertisement-Service" and "DHCPv6-Service". I also think openwrt was still advertising the IPv6 DNS addresses (2001:4860:4860::8888) even though it wasn't possible to query those servers. In all honestly it was bad configuration on my end, I'm still getting my head around IPv6. It doesn't help that my ISP (BT) do some odd things - see [here](https://www2.warwick.ac.uk/fac/sci/csc/people/computingstaff/jaroslaw_zachwieja/bt_fttc_ipv6/).

**Comment by FooDeas** [comment] 2017-10-04 12:34
Please create an issue for disabling ~~IPv4~~ IPv6 at all. Would you test it if I implement this feature?

**Comment by mpmc** [comment] 2017-10-04 21:19
@FooDeas - absolutely I have no issue breaking my network again!

**Comment by thijstriemstra** [comment] 2017-10-06 03:20
Tested with an older rpi:

```
==================================================
raspberrypi-ua-netinst
==================================================
Revision v2.0.0_RC1 (19430c7)
Built on vr  6 okt 2017  2:04:25 CEST
Running on Raspberry Pi version B+
==================================================
https://github.com/FooDeas/raspberrypi-ua-netinst/
==================================================
```
Everything's fine;

```
Configuring apt:
  Configuring Raspbian repository... OK
  Checking Raspbian repository entry... OK
  Adding raspberrypi.org GPG key to apt-key... OK
  Configuring RaspberryPi repository... OK
  Configuring RaspberryPi preference... OK
```

and then; the custom repo I tested this with warned about not being able to parse the pgp key (?):

```
  Copying './foo.apt.list' to /etc/apt/sources.list.d/... OK
  Adding key './foo.gpg.key' to apt.Warning: apt-key output should not be parsed (stdout is not a terminal)
OK
OK
  Copying './01proxy' to /etc/apt/apt.conf.d/... OK
```
And then it dies with errors related to old packages specified on my side:

```
Updating package lists... OK

Downloading packages...
  Reading package lists...
  Building dependency tree...
  Reading state information...
  E: Unable to locate package libinput5
```

which I'll fix.

So looks good except for the `apt-key` warning (error?).

**Comment by FooDeas** [comment] 2017-10-09 22:33
We have to ignore the apt-key warning because stdout tees to serial and log. But the output itself is ugly...

**Comment by bengtfredh** [comment] 2017-10-12 10:46
raspberrypi-ua-netinst v2.0.0 RC2:
root_ssh_pwlogin=1 has no effect.
root login ssh with password not enabled.

**Closed as completed** 2017-10-15 23:08 UTC
Labels: enhancement

**Comment by thijstriemstra** [comment] 2017-10-15 23:27
> We have to ignore the apt-key warning because stdout tees to serial and log. But the output itself is ugly...

Ok but was it properly executed? (**Update**: looks like you already improved the log message in https://github.com/FooDeas/raspberrypi-ua-netinst/commit/90f1b83d44dbcba460f57addee458b74a408a83d)

**Comment by FooDeas** [comment] 2017-10-16 00:29
It's a warning only.

**Comment by FooDeas** [comment] 2017-10-16 00:31
More in detail:
Your return type was 0 - no fail here. So it was executed successfully.

**Comment by thijstriemstra** [comment] 2017-10-16 00:32
Thanks for the feedback. I suppose stretch version is more strict with apt-key.
