### ISSUE TITLE
Installation not possible with RTCs

### ISSUE THREAD

**Issue by eLvErDe** [FooDeas/raspberrypi-ua-netinst#116] opened 2017-12-08 14:16 UTC
Hi,

hwclock fails to run. Once installed, I added "dtoverlay=i2c-rtc,mcp7941x" to config.txt and it worked just fine.
I guess there's something missing with installer "boot" environment. Maybe i2c is not enabled, or we're missing some overlays. I'll try to look into a it but your help would be welcome.

Regards, Adam.

**Comment by eLvErDe** [comment] 2017-12-08 14:48
Adding

```
dtparam=i2c_arm=on
```

Did not help.

When getting into the emergency initrd shell, hwclock says: cannot access /dev/misc/rtc
dmesg has no reference to i2c or rtc :/

I don't have much more ideas...

**Comment by FooDeas** [comment] 2017-12-09 20:19
I don't see why, because I have no installer-config.txt from you. :)
Did you use `rtc=mcp7941x` there?

**Comment by eLvErDe** [comment] 2017-12-09 20:41
Yes exactly and I noticed the installer restarts once to add dtolverlay=i2c-rtc,mcp7941x but then hwclock does not work.

I replaced "| fail" by "| true" and the installation went fine and clock was working properly at first boot.

**Comment by FooDeas** [comment] 2017-12-09 20:58
Looks like a missing dependency in the stretch installer environment...

**Comment by eLvErDe** [comment] 2017-12-09 21:06
Is there any way to see if the kernel actually sees the I2C clock ?
I'm still thinking about something kernel/overlays related...

**Comment by FooDeas** [comment] 2017-12-09 21:20
i2cdetect from i2c-tools should help here.

**Comment by eLvErDe** [comment] 2017-12-09 21:28
Yes but it's not available in installer initrd

**Comment by FooDeas** [comment] 2017-12-09 21:31
Right you've to copy that in place manually. I'm checking the problem with an ds3231 on a B+ and report.

**Comment by FooDeas** [comment] 2017-12-09 21:34
Problem confirmed.

**Comment by FooDeas** [comment] 2017-12-09 22:07
Checkout and try the current devel branch. I'm still testing but think, it should be fixed.

**Comment by eLvErDe** [comment] 2017-12-09 22:10
Cannot do at the moment. Friday for sure, but I'll try to have a colleague feedback on Monday.

Thanks !

**Comment by FooDeas** [comment] 2017-12-10 00:30
Successfully tested with DS3231 on 7ffcaf3. Please report.

**Closed as completed by FooDeas** 2017-12-10 00:30 UTC
Labels: bug

**Comment by eLvErDe** [comment] 2017-12-12 09:31
Hi,

Installation seems to start fine when moving to devel branch so I guess it's fixed.
Test has been done by a colleague but we confirmed it was failing, then switched branch and confirm installation continues so I think it's fine.

Thanks a lot for this great fork.

Adam.
