### ISSUE TITLE
f2fs can't be loaded

### ISSUE THREAD

**Issue by sidey79** [FooDeas/raspberrypi-ua-netinst#138] opened 2018-03-08 20:26 UTC
https://github.com/FooDeas/raspberrypi-ua-netinst/blob/d50d417d22d8fd4ba47af24fca153f517d6dda80/scripts/opt/raspberrypi-ua-netinst/install.sh#L1503

Script hangs on release 2.1.0 while trying to load f2fs module.

Bevore it can't change to the right verson of the libs.
4.9.59 is on the filesystem but it tries for /lib/modules/4.9.24-v7  which doesn't exists

**Comment by FooDeas** [comment] 2018-03-16 01:03
I'll check that next week. Did you build the installer by yourself or used the latest release?

**Comment by sidey79** [comment] 2018-03-16 06:53
I used the latest Release .

**Comment by Mausy5043** [comment] 2018-03-18 12:23
try a different SD-card.

**Comment by sidey79** [comment] 2018-03-18 12:27
I have currently no other available.
But with Release 2.0 IT works

**Comment by Mausy5043** [comment] 2018-03-18 12:30
Remarkable. I've built from the `devel` branch this weekend several times without any issues.

**Comment by napo67** [comment] 2018-03-20 09:52
I saw this issue when I was doing a reinstall, so it definitely exists. The issue is also reproducible every time.

**Comment by sidey79** [comment] 2018-03-20 17:20
Yes, that ist exactly what i tried. Reinstall a cortupted System on a new SD card

**Comment by napo67** [comment] 2018-03-20 18:31
I was doing a reinstall as described here since I was updating my installer-config.txt.

https://github.com/FooDeas/raspberrypi-ua-netinst#reinstalling-or-replacing-an-existing-system

**Comment by kpfleming** [comment] 2018-03-27 12:41
I just did two installs from the `devel` branch using f2fs and they worked fine.

**Comment by napo67** [comment] 2018-03-27 12:53
If you build from the devel it will include 4.9.80-v7+ modules so you will not see this issue. It will only happen with the pre-built images.

**Comment by napo67** [comment] 2018-03-30 20:11
Just tried to reinstall from devel branch. It worked once, did not work the second time around:

depmod: can't change directory to 'lib/modules/4.14.30-v7+': No such file or directory
modprobe: can't change directory to '4.14.30-v7+': No such file or directory
...
Applying new partition table... OK
Initializing /boot as vfat... OK
Copying /boot files in... OK
Loading f2fs module... 
Error: The installation could not be completed!

**Comment by kpfleming** [comment] 2018-03-30 21:03
The RPF kernel was just updated from 4.9.x to 4.14.x, but I was able to build and use an installer today with the new kernel, so I don't think that's the problem.

**Comment by napo67** [comment] 2018-03-31 10:33
I think it is. If one does not do a new build when the kernel changes, it will cause issues with reinstall. These updates were available for my rpi3, but I did not do the update because of reinstall:

        libraspberrypi-bin 1.20180328-1
        libraspberrypi0 1.20180328-1
        raspberrypi-bootloader 1.20180328-1
        raspberrypi-kernel 1.20180328-1
        raspberrypi-sys-mods 20180328+1

After the reinstall, the second reinstall attempt failed, probably because the ua-netinst upgraded the packages. I guess the reinstall is using the upgraded kernel and that causes the failure.

**Comment by kpfleming** [comment] 2018-03-31 14:12
It appears that something has changed recently and now the `cpio` package must be explicitly installed, otherwise the build.sh script produces a broken installer. Please confirm that you have that package installed.

**Comment by napo67** [comment] 2018-03-31 15:10
The `cpio` package is not installed on my setup. I will check with the release version with `cpio` installed to see if that makes a difference. Thank you for the info.

Edit: I actually misunderstood you. The missing cpio does not explain why the release from last December fails to reinstall.

**Comment by Mausy5043** [comment] 2018-03-31 16:10
The `cpio` package has not been part of a default installation for a long time.  
When I developed my script to build the installer on a RPi automagically I always made sure to first install `git`, `curl`, `zip` and `cpio`. Usually the first three are already present when I start a build.

**Comment by FooDeas** [comment] 2018-04-03 03:26
I'll prepare a RC of the latest devel. I think that will fix this problem.

**Comment by thijstriemstra** [comment] 2018-04-03 22:34
Or is this a duplicate of #147?

**Comment by FooDeas** [comment] 2018-04-04 08:10
Please test with the pre-release: [v2.2.0 RC1](https://github.com/FooDeas/raspberrypi-ua-netinst/releases/tag/v2.2.0_RC1)

**Comment by napo67** [comment] 2018-04-08 11:39
The pre-release installer hangs on a clean install when it is installing libjavascriptcoregtk-4.0-18.
I am installing these packages:

packages=apticron,curl,dnsutils,emacs,emacs-goodies-el,gettext,git,git-crypt,git-doc,gitk,git-gui,htop,jq,locate,make,meld,ntpdate,nullmailer,telnet,xauth,yadm,zsh,zsh-doc

EDIT:

This was caused by  something else than your installer. The RC works.

**Closed as completed** 2018-04-25 10:47 UTC
Labels: bug
